CREATE TABLE IF NOT EXISTS magentoImport (	
id INTEGER PRIMARY KEY,
sku TEXT ,
_store TEXT ,
_attribute_set TEXT ,
_type TEXT ,
_root_category TEXT ,
_product_websites TEXT ,
name TEXT ,
price TEXT );

CREATE TABLE IF NOT EXISTS unleashedImport (	
id INTEGER PRIMARY KEY,
productCode TEXT,
productDescription TEXT,
notes TEXT,
barcode TEXT,
units TEXT,
minStockAlertLevel TEXT,
maxStockAlertLevel TEXT,
binLocation TEXT,
labelTemplate TEXT,
supplierCode TEXT,
supplierName TEXT,
supplierProductCode TEXT,
defaultPurchasePrice REAL,
minimumOrderQuantity TEXT,
minimumSaleQuantity TEXT,
defaultSellPrice REAL,
minimumSellPrice REAL,
sellPrice1 REAL,
sellPrice2 REAL,
sellPrice3 REAL,
sellPrice4 REAL,
sellPrice5 REAL,
sellPrice6 REAL,
sellPrice7 REAL,
sellPrice8 REAL,
sellPrice9 REAL,
sellPrice10 REAL,
packSize TEXT,
weight TEXT,
width TEXT,
height TEXT,
depth TEXT,
lastCost REAL,
neverDiminishing TEXT,
productGroup TEXT,
salesAccount TEXT,
COGSAccount TEXT,
purchaseAccount TEXT,
purchaseTaxType TEXT,
purchaseTaxRate TEXT,
salesTaxType TEXT,
saleTaxRate TEXT,
isAssembledProduct TEXT,
isComponent TEXT,
isObsoleted TEXT,
isSellable TEXT,
isApiProduct TEXT,
apiProductType TEXT);


